### ISSUE TITLE
Pre-hashing is generally bad.

### ISSUE THREAD

**Issue by void-azure** [paragonie/password_lock#24]
This is a dangerous (but common) practice that should be avoided due to password shucking.

https://github.com/paragonie/password_lock/blob/11ea1ae344e64c2b591f4cd7488d78d7632064f1/src/PasswordLock.php#L53-L59

You can read more about it on the OWASP cheatsheet for password storage.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pre-hashing-passwords

Regards, Azure

**Comment by void-azure** [comment]
As far as I am concerned you can't exceed 72 bytes.

**Comment by paragonie-security** [comment]
When OWASP discusses pre-hashing passwords, they're generally concerned about client-side hashing, not remarking on the exact server-side password storage algorithm.

The DEFCON talk about **password shucking** was about an insecure password hash migration strategy, where you take an existing database of insecurely hashed passwords and then bcrypt the existing plaintext hashes. This makes the old, insecure hash a password-equivalent and if the hash is insecure enough (hello MD5), you're going to have a bad time.

With password shucking, if you have an existing database of `user:md5(password)` and the updated system uses `bcrypt(md5(password))`, you only have to attack the MD5 hash to figure out the real password.

## Neither of these concerns are applicable to password_lock.

Aside from the fact that SHA-384's output is sufficiently large (while MD5's is not) to side-step the optimized attacks, password_lock never *stores* the plaintext SHA-384. The migration-oriented concerns are obviated due to the context of what we're doing.

Additionally, SHA-384 isn't a commonly used hash function by clueless developers that might have stored a cryptographic hash of the password (although this ecosystem observation is *not* true of MD5, SHA-256, and SHA-512, but we don't use those hash functions).

OWASP is often very confused about a lot of things, especially cryptography. When faced with ambiguity, they try to offer advice that errs on the side of caution, which leads to telling people not to do things that aren't inherently unsafe to do.

**Comment by void-azure** [comment]
Fair enough i am going to close this issue. I would pin this issue to prevent duplicates. Thanks @paragonie-security.

Regards, Azure
