### ISSUE TITLE
Hash length is longer than allowed bcrypt input

### ISSUE THREAD

**Issue by polonskiy** [paragonie/password_lock#4]
Bcrypt is limited to 72 characters and you have 88:
```
$ php -r 'var_dump(strlen(base64_encode(hash("sha512", "foo", true))));'
int(88)
```

**Comment by polonskiy** [comment]
@ircmaxell
From #3:
> Eih, 256 bits of entropy is fine for a password. That is way outside of guess ability anyway. If we were designing from scratch, sure, 512 is measurably better.

I think sha512 is not usable with bcrypt.
* you can't use raw sha512 output (64 bytes) - it is not NUL-byte safe
* encoded sha512 output is longer than 72 bytes (base64, base85)

**Comment by paragonie-scott** [comment]
> I think sha512 is not usable with bcrypt.

Given 512 = 88 bytes of output, truncating to 72 bytes would be 432 bits of preserved entropy. Unless there's some weakness in SHA512 that makes it easier to guess the first N/M bytes than the latter (M-N)/M bytes, I don't see this as a weakness.

For the record 432 bits is more than most people's passwords (except my LUKS keys), so this shouldn't degrade security at all. :)

**Comment by polonskiy** [comment]
> truncating to 72 bytes would be 432 bits of preserved entropy

I am not sure, that hash truncation is safe.

Do you think that half of sha512 is secure as sha256? Or two sha256 is the same as sha512?

**Comment by paragonie-scott** [comment]
> Do you think that half of sha512 is secure as sha256?

[Yes](http://ed25519.cr.yp.to/ed25519-20110926.pdf).

**Comment by ircmaxell** [comment]
> Do you think that half of sha512 is secure as sha256? Or two sha256 is the same as sha512?

If it wasn't, then that would be a complete and total break for SHA-2 (in all, not just 256 or 512) since it would be a method to bypass the [Avalanche effect](https://en.wikipedia.org/wiki/Avalanche_effect) which would fundimentally undermine the security of the algorithm and expose serious design flaws.

In other words, if truncating 1/2 of sha-512 is weaker than sha-256, both are by very definition broken (since they are the same algorithm under the hood).

**Comment by polonskiy** [comment]
You are right. Thanks.
